import Foundation

/// 食材名 → 素材 id 和给 Image Playground 的英文描述。
/// 和 `Bingxiang/Data/FoodCatalog.swift` 里的 `art` 字段对应。
let foodArtCatalog: [(name: String, id: String, prompt: String)] = [
    ("番茄", "tomato", "a single ripe red tomato"),
    ("黄瓜", "cucumber", "a single fresh cucumber"),
    ("生菜", "lettuce", "a head of fresh green lettuce"),
    ("西兰花", "broccoli", "a head of broccoli"),
    ("土豆", "potato", "a single potato"),
    ("胡萝卜", "carrot", "a single carrot"),
    ("青椒", "green-pepper", "a green bell pepper"),
    ("洋葱", "onion", "a single yellow onion"),
    ("大蒜", "garlic", "a bulb of garlic"),
    ("小葱", "scallion", "a bunch of green scallions"),
    ("芹菜", "celery", "a bunch of celery"),
    ("韭菜", "chives", "a bunch of garlic chives"),
    ("香菇", "mushroom", "a box of shiitake mushrooms"),
    ("冬瓜", "winter-melon", "a slice of winter melon"),
    ("豆腐", "tofu", "a block of tofu in a plastic box"),
    ("玉米", "corn", "an ear of corn"),
    ("菠菜", "spinach", "a bunch of fresh spinach"),
    ("苹果", "apple", "a single red apple"),
    ("香蕉", "banana", "a bunch of bananas"),
    ("橙子", "orange", "a single orange"),
    ("葡萄", "grapes", "a bunch of purple grapes"),
    ("草莓", "strawberry", "a small box of strawberries"),
    ("西瓜", "watermelon", "a slice of watermelon"),
    ("蓝莓", "blueberry", "a small box of blueberries"),
    ("柠檬", "lemon", "a single lemon"),
    ("猕猴桃", "kiwi", "a single kiwi fruit"),
    ("猪肉", "pork", "a pack of raw pork on a tray"),
    ("牛肉", "beef", "a pack of raw beef steak on a tray"),
    ("鸡胸肉", "chicken-breast", "a pack of raw chicken breast on a tray"),
    ("鸡翅", "chicken-wings", "a pack of raw chicken wings on a tray"),
    ("排骨", "pork-ribs", "a pack of raw pork ribs on a tray"),
    ("培根", "bacon", "a pack of bacon"),
    ("火腿", "ham", "a pack of sliced ham"),
    ("香肠", "sausage", "a pack of sausages"),
    ("虾仁", "shrimp", "a bag of frozen shrimp"),
    ("鱼", "fish", "a whole fresh fish"),
    ("三文鱼", "salmon", "a salmon fillet on a tray"),
    ("鸡蛋", "egg", "a carton of eggs"),
    ("牛奶", "milk", "a carton of milk"),
    ("酸奶", "yogurt", "a cup of yogurt"),
    ("黄油", "butter", "a block of butter"),
    ("奶酪", "cheese", "a wedge of cheese"),
    ("可乐", "cola", "a bottle of cola"),
    ("橙汁", "orange-juice", "a bottle of orange juice"),
    ("啤酒", "beer", "a can of beer"),
    ("豆浆", "soy-milk", "a bottle of soy milk"),
    ("番茄酱", "ketchup", "a bottle of ketchup"),
    ("蚝油", "oyster-sauce", "a bottle of oyster sauce"),
    ("沙拉酱", "salad-dressing", "a bottle of salad dressing"),
    ("果酱", "jam", "a jar of strawberry jam"),
    ("豆瓣酱", "bean-paste", "a jar of chili bean paste"),
    ("剩饭", "leftover-rice", "a food container of cooked rice"),
    ("剩菜", "leftovers", "a food container with leftover dishes"),
    ("外卖", "takeout", "a takeout food box"),
    ("蛋糕", "cake", "a slice of cake"),
    ("面包", "bread", "a loaf of bread"),
    ("面条", "noodles", "a bag of fresh noodles"),
    ("燕麦", "oats", "a bag of oats"),
    ("紫菜", "seaweed", "a pack of dried seaweed"),
    ("速冻水饺", "dumplings", "a bag of frozen dumplings"),
    ("冰淇淋", "ice-cream", "a tub of ice cream"),
    ("冷冻蔬菜", "frozen-vegetables", "a bag of frozen mixed vegetables"),
    ("冻肉", "frozen-meat", "a pack of frozen meat"),
    ("汤圆", "tangyuan", "a bag of frozen glutinous rice balls"),
]
